#!/usr/bin/env bash

set -ex

# TODO: plunder save sire.main > sire.seed

plunder save sire.seed sire/sire.sire

cat sire/??_*.sire | plunder repl sire.seed --save out.seed

sha1sum out.seed sire.seed

cmp out.seed sire.seed

echo SIRE QUINES
