#!/usr/bin/env bash

set -ex

stack install

if [ "$1" = --no-cache ]
then
    rm -f sire.cache
fi

sh/sire-load-all -M </dev/null
sh/rex-test
sh/testdemo-cog-asktell-basic
sh/testdemo-cog-asktell-askcrash
