#!/usr/bin/env bash

set -ex

stack install

if [ "$1" = --no-cache ]
then
    rm -f sire.cache
fi

sh/sire-load-all </dev/null

# TODO: sh/sire-load-all should exit with an error code if something
# failed!

sh/rex-test
