#!/usr/bin/env bash

set -e

usage () {
    echo "usage: $0 [--no-cache]"
    exit 1
}

if [ "$#" -eq 1 ] && [ "$1" = --no-cache ]
then
    rm -f sire.cache
elif [ "$#" -ne 0 ]
then
    usage
fi

cleanup () { rm -f errout; }
trap cleanup EXIT

runtest () {
    "$@" 2>errout || {
        echo ERROR OUTPUT
        echo ============
        echo
        cat errout
        exit 1
    }
}

set -x

stack install

ulimit -n 55555 # or else fulltag sometimes fails

sh/sire-load-all -M </dev/null
runtest sh/full-tag-site-demo --ci
sh/testdemo-cog-asktell-basic
sh/testdemo-cog-asktell-askcrash
sh/testdemo-cog-wait
sh/rex-test
sh/bootstrap-sire
