#!/usr/bin/env bash

#
# see instructions in `sh/demo_portcat_file_recv`
#

if [ "$#" -ne 1 ]; then
    echo "usage: $0 <FILE>"
    exit 1
fi
FILE=$1

SIZE=$(wc -c <"$FILE")
# send file size as u64 binary, then send file contents
(perl -e "print pack \"Q<*\", $SIZE"; cat $FILE) | stack run pc 111 50430935688763393736507892600132401748281405403404496427106007611588071457755
