#!/usr/bin/env bash

#
# To run this demo:
#
#   1. in one term:     `stack run localhost-router`
#   2. in another term: `sh/demo_portcat_file_recv`
#   3. in another term: `sh/demo_portcat_file_send <FILE>`
#      this will use `pc` to send a file to the ship.
#

export MACHINE_DIR=$(realpath .demo)

plunder=$(stack path --local-install-root)/bin/plunder

rm -Rf "$MACHINE_DIR"
mkdir -p "$MACHINE_DIR"

$plunder boot "$MACHINE_DIR" sire/demo_portcat_file_recv.sire

$plunder start "$MACHINE_DIR" &
RUN_MACHINE=$!

trap 'kill $RUN_MACHINE; exit' INT

wait $RUN_MACHINE
