#!/usr/bin/env bash

set -ex

tmp=$(mktemp -u .demo-XXXXXXX)

cleanup () { rm -rf "./$tmp"; }
trap cleanup EXIT

plunder boot "./$tmp" sire/demo_http_hello.sire --start

-- TODO: get port
-- TODO: write file
-- TODO: read file (assert equal to upload)
-- TODO: read other file (404)
-- TODO: LIST request
-- TODO: POST /shutdown
