#!/usr/bin/env bash

#
# To run this demo, see instructions in `sh/demo_port_localhost_streamer_ali`.
#

# plunder consumes a ton of file descriptors and mmap segments, in the current
# demo design. we must check that we have enough fds for all files, and that we
# have a high enough max_map_count.

# Set a minimum required limit
MIN_LIMIT=55555

# Get the current limit for the number of open files
current_limit=$(ulimit -n)

if [ "$current_limit" -lt "$MIN_LIMIT" ]; then
  echo "Error: The current limit for the number of open files is too low ($current_limit)."
  echo "Please increase the limit to at least $MIN_LIMIT by running the following command:"
  echo "ulimit -n $MIN_LIMIT"
  echo "Note: This change will only apply to the current shell session."
  exit 1
fi

export MACHINE_DIR=$(realpath .demo_bob)

plunder=$(stack path --local-install-root)/bin/plunder

rm -Rf "$MACHINE_DIR"
mkdir -p "$MACHINE_DIR"

$plunder boot "$MACHINE_DIR" sire/demo_port_localhost_streamer_bob.sire

$plunder start "$MACHINE_DIR" &
RUN_MACHINE=$!

until find "$MACHINE_DIR" -maxdepth 1 -name "*.http.port" -quit
do
     echo "Waiting..."
     sleep 0.1
done

# Why an additional sleep here? Some weird filesystem sync issue where the
# port file was created, but hasn't been written to yet.
sleep 0.1

PORT=$(cat "$MACHINE_DIR"/*.http.port)

echo "Setting interface files..."
curl --data-binary @./demo/port-streamer-ui/main.js -H "Content-Type: text/javascript" -X PUT http://localhost:$PORT/main.js
curl --data-binary @./demo/port-streamer-ui/index.html -H "Content-Type: text/html" -X PUT http://localhost:$PORT/index.html
curl --data-binary @./demo/port-streamer-ui/favicon.ico -H "Content-Type: image/x-icon" -X PUT http://localhost:$PORT/favicon.ico

echo "Interface files are set. Running on http://localhost:$PORT/index.html"

wait $RUN_MACHINE
