#!/usr/bin/env bash

#
# To run this demo:
#
#   1. in one term:     `stack run localhost-router`
#   2. in another term: `sh/demo_port_localhost_ali`
#   3. in another term: `sh/demo_port_localhost_bob`
#
#   It's important to boot ali first, since she runs serv, and bob runs rqst.
#

export MACHINE_DIR=$(realpath .demo_bob)

plunder=$(stack path --local-install-root)/bin/plunder

rm -Rf "$MACHINE_DIR"
mkdir -p "$MACHINE_DIR"

$plunder boot "$MACHINE_DIR" sire/demo_port_localhost_bob.sire

$plunder start "$MACHINE_DIR"
