#!/usr/bin/env bash

#
# To use this script, run `rm -Rf .demo/ && plunder server .demo`
# and then run this script in a different terminal from the root of the
# repository with `sh/parallel-mandelbrot-demo`.
#

# Only operate on the `.demo` directory.
export PLUNDER_DIR=$(realpath .demo)

plunder=$(stack path --local-install-root)/bin/plunder

# TODO: error out if this broke.
$plunder boot pfract sire/demo_parallel_mandelbrot.sire
$plunder spin pfract

until [ -f ./.demo/pfract.http.port ]
do
     sleep 1
done

PORT=$(cat .demo/pfract.http.port)

echo "Running on http://localhost:$PORT/index.html"
