#!/usr/bin/env bash

#
# To run the demo, just run `sh/parallel-mandelbrot-demo` from the root of the
# repository.
#

# Only operate on the `.demo` directory.
export MACHINE_DIR=$(realpath .demo)

plunder=$(stack path --local-install-root)/bin/plunder

rm -Rf "$MACHINE_DIR"
mkdir -p "$MACHINE_DIR"

waited=0
until [ -d "$MACHINE_DIR" ]
do
    if [ $waited -eq 0 ]; then
        echo "Waiting for .demo directory to be created"
        waited=1
    fi

    sleep 0.1
done

# TODO: error out if this broke.
$plunder boot "$MACHINE_DIR" sire/demo_parallel_mandelbrot.sire

$plunder start "$MACHINE_DIR" &
RUN_MACHINE=$!

until find "$MACHINE_DIR" -maxdepth 1 -name "*.http.port" -quit
do
     echo "Waiting..."
     sleep 0.1
done

# Why an additional sleep here? Some weird filesystem sync issue where the
# port file was created, but hasn't been written to yet.
sleep .1

PORT=$(cat "$MACHINE_DIR"/*.http.port)

echo "Running on http://localhost:$PORT/index.html"
