#!/usr/bin/env bash

# This test parses and re-prints all the Sire files using
# both Haskell's implementation of Rex and rex-in-sire.  If
# this succeed, we diff the results and error out if any
# differences are detected.

set -e

plunder save rex.seed 25_rex

for x in sire/*.sire
do
        echo rex_test $x
        plunder repl rex.seed <$x >$x.new 2>/dev/null
        rex <$x >$x.old
        diff $x.new $x.old

        rm $x.new $x.old
done

rm -f rex.seed

echo ALL REX TESTS PASSED
