#!/usr/bin/env bash

#
# To run the demo, just run `sh/mandelbrot-ui-demo` from the root of the
# repository.
#

# Only operate on the `.demo` directory.
export MACHINE_DIR=$(realpath .demo)

plunder=$(stack path --local-install-root)/bin/plunder


rm -Rf "$MACHINE_DIR"
mkdir -p "$MACHINE_DIR"

# Ensure the elm files are built.
if ! [ -f ./elm/runcog-demo/index.html ]; then
    nix-shell -p elmPackages.elm --run "cd ./elm/runcog-demo && sh/build"
elif [ ./elm/runcog-demo/src/Main.elm -nt ./elm/runcog-demo/index.html ]; then
    nix-shell -p elmPackages.elm --run "cd ./elm/runcog-demo && sh/build"
fi

waited=0
until [ -d "$MACHINE_DIR" ]
do
    if [ $waited -eq 0 ]; then
        echo "Waiting for .demo directory to be created"
        waited=1
    fi

    sleep 0.1
done

# TODO: error out if this broke.
plunder boot "$MACHINE_DIR" sire/demo_runcog_site.sire

plunder start "${MACHINE_ARGS[@]}" "$MACHINE_DIR" &
RUN_MACHINE=$!

echo "started..."

until find "$MACHINE_DIR" -maxdepth 1 -name "*.http.port" -quit
do
     echo "Waiting..."
     sleep 0.1
done

# Why an additional sleep here? Some weird filesystem sync issue where the
# port file was created, but hasn't been written to yet.
sleep 0.1

PORT=$(cat "$MACHINE_DIR"/*.http.port)

echo "Setting interface files..."
curl --data-binary @./elm/runcog-demo/index.html -H "Content-Type: text/html" -X PUT http://localhost:$PORT/

echo "Interface files are set. Running on http://localhost:$PORT/"

wait $RUN_MACHINE
