#!/usr/bin/env bash

set -e

DEMO=demo_cog_wait

PIER=.test_${DEMO}

OUTPUT=${DEMO}_stdout

rm -rf "$PIER"

plunder boot "$PIER" sire/$DEMO.sire >/dev/null 2>/dev/null

plunder start "$PIER" >/dev/null 2>$OUTPUT

rm -rf "$PIER"

ok=$(grep "PASS" <$OUTPUT | wc -l)

if [ "$ok" = 1 ]
then
    echo "TEST SUCCESS: $DEMO"
else
    echo
    cat $OUTPUT
    echo
    echo "TEST FAILED: $DEMO"
fi

rm -rf "$OUTPUT"

[ "$ok" = 1 ]
