#!/usr/bin/env bash

set -ex

elm make src/Main.elm --optimize --output=elm.opt.js

magic='pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe'

uglifyjs elm.opt.js --compress "$magic" |
    uglifyjs --mangle --output elm.opt.min.js

